all:
	g++ sh_read.c  -o read.out
	g++ sh_write.c  -o write.out
	echo "!Please start read.out in another console"
	./write.out
	rm write.out
	rm read.out
compile:
	g++ sh_read.c  -o read.out
	g++ sh_write.c -o write.out
debug:
	echo "Write debug make"